# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.4
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.5.0-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "MIG-b22e1d08-eaa2-535f-a91b-68a0b3abefb2"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda,cap=sm_80,gpu=a100,cap=recent
      - --name=gpuci.4
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.4:/root
