# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.13
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.5.0-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "MIG-bece94a0-6f70-5e40-b71b-a60fa53aab6f"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda,cap=sm_80,gpu=a100,cap=recent
      - --name=gpuci.13
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.13:/root
